@startuml

title API Endpoint Design

group index

    Client -> Server: GET::index
    Server --> Client: landing.html
    note over Server: User not logged in.

    Client -> Server: POST::index (invalid username)
    Server --> Client: landing.html
    note over Server: User still not logged in. Show failed login error

    Client -> Server: POST::index (valid username)
    Server --> Client: client.html
    note over Server
        Combination of browser cookies and API requests will load
        the client with the user's details.
    end note

group version

    Client -> Server: GET::api/version
    Server --> Client: {'version': '0.1'}

group randomImage (login required)

    Client -> Server: GET::api/randomImage
    Server --> Client: {'image': '_assets/RANDOMPATH'}
    note over Server
        RANDOMPATH is a path to a randomly chosen image in the "_assets"
        directory.
    end note

group randomActionImage (login required)

    Client -> Server: GET::api/randomActionImage
    Server --> Client: {'image': '_assets/action/RANDOMPATH'}
    note over Server
        RANDOMPATH is a path to a randomly
        chosen image in the "_assets/action"
        directory.
    end note

group randomInventoryImage (login required)

    Client -> Server: GET::api/randomInventoryImage
    Server --> Client: {'image': '_assets/multi/inventory/RANDOMPATH'}
    note over Server
        RANDOMPATH is a path to a
        randomly chosen image in the
        "_assets/multi/inventory" directory.
    end note

group logout

    Client -> Server: GET::logout
    Server --> Client: landing.html

group sysmsg

    Client -> Server: GET::sysmsg
    Server --> Client: return EventStream socket

group location (login required)

    Client -> Server: GET::api/location  (valid login)
    Server --> Client: return LocationResponse
    note over Server
        Map zoom level is sent as part of POST request, here assume 3x3.
        Also, "tile_-1,+1" represents a path to the tile image for the
        location x-1, y+1 where x and y are the current
        location of the user.
        Finally, the map icons list describes the overlay
        icons to show overtop of the associated map tile.

        .LocationResponse = {
        .  'action': {'asset': 'path/to/image',
        .             'title': 'name of thing',
        .             'notes': 'recommended level and or tool'},
        .  'map': [['tile_-1,+1', 'tile_0,+1', 'tile_1,+1'],
        .          ['tile_-1,0', 'tile_0,0', 'tile_1,0'],
        .          ['tile_-1,-1', 'tile_0,-1', 'tile_1,-1']],
        .  'map_icons': [[None, None, 'person'],
        .                [None, None, None],
        .                [None, None, None]]
        .}
    end note

group move (login required)

    Client -> Server: POST:api/move {'direction': 'north'}
    Server --> Client: move user in DB, redirect "location"

@enduml
